myfirst/apps/project/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('comments/', views.comments, name='comments'),
    path('answer_list/', views.articles, name='answer_list'),
    path('menu/', views.menu, name='menu'),
    path('authors/', views.authors, name='authors'),
    path('articles/add', views.leave_quest, name='leave_quest'),
    path('articles/new', views.addart, name='addart'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment'),
]

myfirst/urls.py
from . import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('', include('project.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myfirst/apps/project/models.py
from django.db import models

from django.utils import timezone


class Article(models.Model):
    article_author = models.CharField('Автор', max_length=200)
    article_photo = models.ImageField('Изображение')
    article_title = models.CharField('Название вопроса', max_length=200)
    article_text = models.TextField('Текст вопроса', max_length=15000)
    pub_date = models.DateTimeField('Дата публикации')
    
    def __str__(self):
        return self.article_title

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопрос'


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField('Имя автора', max_length=75)
    comment_text = models.CharField('Текст комментария', max_length=500)
    comment_date = models.DateTimeField('Дата ответа')

    def __str__(self):
        return self.author_name

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

myfirst/apps/project/views.py
from django.http import Http404, HttpResponseRedirect

from django.urls import reverse

from django.shortcuts import render

from datetime import datetime

from .models import Article, Comment


def index(request):
    latest_articles_list = Article.objects.order_by('-pub_date')[:5]
    return render(request, 'index.html', {'latest_articles_list': latest_articles_list})


def detail(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Статья не найдена!")
    latest_comment_list = a.comment_set.order_by('-id')[:10]
    return render(request, 'project/detail.html', {'article': a, 'latest_comment_list': latest_comment_list})


def comments(request):
    comment = Comment.objects.all()
    return render(request, 'project/list.html', {'comments': comment})


def articles(request):
    article = Article.objects.all()
    return render(request, 'project/answer_list.html', {'articles': article})


def menu(request):
    return render(request, 'project/menu.html')
    
def leave_quest(request):
    return render(request, 'project/addanswer.html')

def authors(request):
    return render(request, 'project/authors.html')

def leave_comment(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Статья не найдена!")
    a.comment_set.create(author_name=request.POST['name'], comment_text=request.POST['text'], comment_date=datetime.now())
    return HttpResponseRedirect(reverse('articles:detail', args=(a.id,)))
    
def addart(request):
    a = Article.objects.create(article_author=request.POST['author'], article_title=request.POST['title'], article_text=request.POST['text'], article_photo=request.FILES['photo'], pub_date=datetime.now())
    return HttpResponseRedirect(reverse('articles:detail', args=(a.id,)))

myfirst/templates/base.html
{% load static %}
<DOCTYPE html>
<html lang="ru">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>{% block title %}Мой сайт{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
</head> 
<body>
	<div id="wrapper">
		<div id="header"></div>
		<ul id="nav">
			<li><a href="{% url 'articles:index'%}" >Главная</a></li>
			<li><a href="{% url 'articles:leave_quest'%}" >Оставить новый вопрос</a></li>
			<li><a href="{% url 'articles:comments'%}" >Все ответы</a></li>
			<li><a href="{% url 'articles:answer_list'%}" >Все вопросы</a></li>
			<li><a href="{% url 'articles:menu'%}" >Меню</a></li>
			<li><a href="{% url 'articles:authors'%}" >Об авторах</a></li>
		</ul>
			<div id="content" class="clearfix">
	{% block content %}ss{% endblock %}
			</div>
	
	</div>	
</body>
</html>

myfirst/templates/index.html
{% extends 'base.html' %}

{% block title %}Форум взаимопомощи{% endblock %}
{% block content %}
    <div id="col_2">
	{%if latest_articles_list %}
		{% for a in latest_articles_list %}
			<div>
				<p id ="textstyle">
					<a href="{% url 'articles:detail' a.id %}" style="font-size:12"><font color="#FF6347" face="Arial">{{a.article_title}}</font></a><br>
					<a style="font-size:10;">{{a.article_author}}, {{a.pub_date}}, <a style="font-size:10;" href="{% url 'articles:detail' a.id %}"> оставить ответ ✏</a></a>
					<hr>
				</p>
			</div>
		{% endfor %}
	{% else %}
		Вопросы не найдены
	{% endif %}  
	</div>
</div>
{% endblock %}	

myfirst/templates/project/addanswer.html
{% extends 'base.html' %}

{% block title %}{{article.article_title}}{% endblock %}

{% block content %}
	<div id="col_2">
		<form action = "{% url 'articles:addart'%}" enctype="multipart/form-data" method ="POST">
			<br>
			{% csrf_token %}
			<input type = "text" required placeholder = "Ваше имя" name = "author"><br><br>
			<textarea name="title" required="" placeholder = "Название вопроса" id="" cols="82" rows="5"></textarea><br><br>
			<textarea name="text" required="" placeholder = "Текст вопроса" id="" cols="82" rows="10" ></textarea><br><br>
			<p><input type="file" name="photo" ></p>
			<button type="submit">Оставить новый вопрос</button>
		</form>
{% endblock %}
</div>

myfirst/templates/project/answer_list.html
{% extends 'base.html' %}

{% block title %}Все вопросы{% endblock %}

{% block content %}

	{%if articles %}
		
		{% for a in articles %}
		<p>
			<p>Название <a href="{% url 'articles:detail' a.id %}"><font color="#FF6347" face="Arial">{{a.article_title}}</font></a></p>
			<p>Автор <font color="#FF6347" face="Arial">{{a.article_author}}</font></p>
			<p>Дата <font color="#FF6347" face="Arial">{{a.pub_date}}</font></p>
			<hr>
		</p>
		{% endfor %}
		
	{% else %}
		Вопросы не найдены
	{% endif %}
{% endblock %}

myfirst/templates/project/authors.html
{% extends 'base.html' %}

{% block title %}Все ответы{% endblock %}

{% block content %}

		<p>
		
		</p>

{% endblock %}

myfirst/templates/project/detail.html
{% extends 'base.html' %}

{% block title %}{{article.article_title}}{% endblock %}

{% block content %}
	<div id="col_2">
		<h2>{{article.article_title}}</h2>
		<p align="center"><img src="{{article.article_photo.url }}"></p>
		<p>{{article.article_text}}</p>
		<p align="right" style="font-size:10">{{article.pub_date}}</p>
		<hr>
		{% if latest_comment_list %}
		{% for c in latest_comment_list%}
			<h2>{{c.author_name}}</h2>
			<p>
				<blockquote>{{c.comment_text}}</blockquote>
				<a style="float:right; font-size:8">{{c.comment_date}}</a>
			</p>
		{% endfor %}
		{% else %}
		{% endif %}
		</hr>

		<form action = "{% url 'articles:leave_comment' article.id %}" method ="POST">
		<hr>
		{% csrf_token %}
		<br>
		<input type = "text" required placeholder = "Ваше имя" name = "name"><br><br>
		<textarea name="text" required="" placeholder = "Текст комментария" id="" cols="82" rows="10"></textarea><br><br>
		<button type="submit">Оставить комментарий</button>
	</form>
{% endblock %}
</div>

myfirst/templates/project/list.html
{% extends 'base.html' %}

{% block title %}Все ответы{% endblock %}

{% block content %}

	{%if comments %}
		
		{% for a in comments %}
		<p>
			<p>К статье <a href="{% url 'articles:detail' a.article.id %}"><font color="#FF6347" face="Arial">{{a.article}}</font></a></p>
			<p>Пользователь <font color="#FF6347" face="Arial">{{a.author_name}}</font></p>
			<p>Написал <font color="#93aa00" face="Arial">{{a.comment_text}}</font></p>
			<hr>
		</p>
		{% endfor %}
		
	{% else %}
		Комментарии не найдены
	{% endif %}
{% endblock %}

myfirst/templates/project/menu.html
{% extends 'base.html' %}

{% block title %}Все ответы{% endblock %}

{% block content %}

		<ul id="subnav">
			<li><a href="{% url 'articles:index'%}" >Главная</a></li>
			<li><a href="{% url 'articles:leave_quest'%}" >Оставить новый вопрос</a></li>
			<li><a href="{% url 'articles:comments'%}" >Все ответы</a></li>
			<li><a href="{% url 'articles:answer_list'%}" >Все вопросы</a></li>
			<li><a href="{% url 'articles:menu'%}" >Меню</a></li>
			<li><a href="{% url 'articles:authors'%}" >Об авторах</a></li>
		</ul>

{% endblock %}